Add a dependabot configuration
PhilanthropyDataCommons/deploy pull request #93
Opened 2023-08-17 17:33 UTC by bickelj

Hopefully dependabot will "just work" but the presence of https://github.com/dependabot/dependabot-core/issues/390 suggest it will not. This repository doesn't have a `Dockerfile`, only a `compose.yml`.

2023-08-29 19:11 UTC, port19x commented
> Hopefully dependabot will "just work" but the presence of [dependabot/dependabot-core#390](https://github.com/dependabot/dependabot-core/issues/390) suggests it will not. This repository doesn't have a `Dockerfile`, only a `compose.yml`.

It won't work btw

2023-08-30 15:31 UTC, slifty commented
@bickelj Should we explore leveraging a Dockerfile in order to get dependabot support (either in this PR or by splitting the docker based dependabot stuff into a new PR)

2023-08-30 15:33 UTC, slifty requested changes
Since it sounds like the `docker` portion of this change won't do anything in the current setup, let's either (A) remove that portion from this PR or (B) also adjust our docker configuration approach so that it uses a Dockerfile.

I'd probably lean towards (A) since that way we at least start getting github-actuion dependabot updates while we work on (B) in another PR.

2023-08-30 17:46 UTC, port19x commented
https://github.com/sbe-arg/simple-compose-service-updates might suit your use-case as well. Not sure how you guys would move a compose stack into a Dockerfile

2023-09-01 14:58 UTC, bickelj commented
@port19x is right: trying to shoehorn a compose script into a Dockerfile is intractable because compose operates at a level higher than already-built docker images.

@slifty I'm still inclined to merge the docker portion along with it. Suppose https://github.com/dependabot/dependabot-core/issues/390 gets fixed. I'd rather dependabot just start working than have to wait for notification of that issue getting fixed and then going back and updating our configuration. But I'm not strongly inclined either way.

2023-09-12 16:23 UTC, slifty commented
@bickelj that's fine!

For now is this PR actionable?  Let's either update it so we can merge it, or close it with the intent to re-open when conditions have resolved.

2023-09-12 20:41 UTC, bickelj commented
@slifty Does it look OK? I rebased on main and added a comment to the commit message indicating why I kept the Docker part in.

2023-09-12 21:06 UTC, bickelj commented
@port19x Thank you for confirming the suspicion that Docker Compose isn't yet working and also for the suggested workaround. Much appreciated!

2023-09-13 01:51 UTC, slifty approved these changes
Sorry it took so long for me to approve this (I had misunderstood the conversation on the PR!)

Thank you @bickelj for the work and for @port19x for weighing in with some context and guidance.

2023-09-13 14:45 UTC, merged